### PR TITLE
New Feature

### PR DESCRIPTION
**Pull request by SuperSweatyTejas**
# Summary
Added a new feature, paginates an array of embeds with 2 buttons!

created functions folder inside of src folder for functions

Edited index file for the new feature / function

# Extra details
I added an example of the readME

# References

video / gif example

Link: https://cdn.discordapp.com/attachments/840619319921737750/870009196173738074/2021-07-28_14-25-11.mp4

### CODE REVIEW

**Comment by RaZegame** [comment]
"sussyEmbed"

**Comment by Assassin-1234** [comment]
cant merge since there are many packages out there doing the exact same + it isnt that hard to make pagination with buttons

we believe in making something ***unique*** and making stuff easier for the user.

sorry 😔

have an ice cream 🍧

**Comment by Assassin-1234** [comment]
also for future pull requests, please use eslint 😳

**Comment by SuperSweatyTejas** [comment]
😢 but i take ice scream

**Comment by SuperSweatyTejas** [comment]
damn, but i take the ice cream

**Pull request closed without merging**
