### PR TITLE
Added slash command support & custom messages to other stuff

### PR DESCRIPTION
**Pull request by ChopChoP534**
### CHANGES: 

**Giveaways-**
`- Nuggies.giveaways.create({ message, prize, hostID, winners, endAfter, requirements = { enabled: false }, channelID })`
`+  Nuggies.giveaways.create(client, { prize, hostID, winners, endAfter, requirements = { enabled: false }, channel })`

`- Nuggies.giveaways.drop({ message, prize, channelID, hostID })`
`+ Nuggies.giveaways.drop(client, { prize, channel, hostID })`

**Button Roles-**
`- Nuggies.buttonroles.create({ message, role, content, channelID })`
`+ Nuggies.buttonroles.create(client, { content, role, channelID })`

**DropDown Role-**
`- Nuggies.dropdownroles.create({ message, role, content, channelID })`
`+ Nuggies.dropdownroles.create(client, { content, role, channelID })`

**Custom Messages Function-**
`- Nuggies.giveaways.Messages(client, {});`
`+ `https://sourceb.in/w2BsAi6EZM it big

there can be some stuff that I forgor to mention

### CODE REVIEW

**Comment by LegItMate** [comment]
Typings aren't updated I suppose?

**Comment by ChopChoP534** [comment]
nope, idk how to ts

**Comment by LegItMate** [comment]
Will have to wait for me then

**Review by LegItMate — CHANGES_REQUESTED** [review]
At [src/classes/v12/dropdownroles.js#3](https://github.com/Nuggies-bot/nuggies-npm/blob/f2377a890b4591949d66153574ee9b1cf56e03dd/src/classes/v12/dropdownroles.js#L3) you seem to have required client from [src/classes/v13/dropdownroles.js](https://github.com/Nuggies-bot/nuggies-npm/blob/f2377a890b4591949d66153574ee9b1cf56e03dd/src/classes/v13/dropdownroles.js) and similar in that same file, but you are not exporting the client.

**Comment by ChopChoP534** [comment]
fixed

**Review by Assassin-1234 — APPROVED** [review]

**Comment by LegItMate** [comment]
At [src/classes/v12/giveaways.js#57](https://github.com/Nuggies-bot/nuggies-npm/pull/64/files#diff-554995234be2b0608a22e08d565c5630fad0ce52087e78e0f872d6fed3646d25R57) you are using `channel` as a TextChannel/Channel but channel is supposed to be snowflake(or ID of the channel)

**Comment by LegItMate** [comment]
ESLint throws an error in [src/classes/v12/dropdownroles.js#48](https://github.com/Nuggies-bot/nuggies-npm/blob/a280db3947c6a1bf6b36a93c8135231d646af16c/src/classes/v12/dropdownroles.js#L48) which is `message is not defined` 
image

**Comment by Assassin-1234** [comment]
can you import discord.js in src/typings/index.ts ? other than that I dont see a problem, @LegItMate merge if everything alryte 👍

**Comment by Assassin-1234** [comment]
didnt meant to close oop

**Comment by LegItMate** [comment]
> can you import discord.js in src/typings/index.ts ? other than that I dont see a problem, @LegItMate merge if everything alryte 👍

It isn't required/used though

**Comment by Assassin-1234** [comment]
> > can you import discord.js in src/typings/index.ts ? other than that I dont see a problem, @LegItMate merge if everything alryte 👍
> 
> It isn't required/used though

eslint gives 69420 errrors

**Comment by Monster3425** [comment]
Which commands of nuggies support slash??

**Comment by Assassin-1234** [comment]
stale or are typings being worked at?

**Review by Assassin-1234 — APPROVED** [review]

**Pull request merged**
