### PR TITLE
Read description

### PR DESCRIPTION
**Pull request by face-hh**
You can not access the object key, if the property itselfs is undefined, however, i use this in v13 and i still get the error, hosting a bot now on repl because i can not find a good hosting, and can not access the node_modules to fix it myself.

### CODE REVIEW

**Comment by face-hh** [comment]
There is also another file that has same error, which i forgot where it is.

**Review by sujalgoel — APPROVED** [review]

**Comment by LegItMate** [comment]
Reason for revert: customMessages is supposed to be used for button-roles, dropdown-roles etc later on. You are using customMessages for giveaways only

**Comment by face-hh** [comment]
How am i supposed to fix it then?

**Comment by LegItMate** [comment]
Just open up an issue, provide code(s) and/or error(s) or ask for help in the support channels(or report bug whichever it may be).

**Comment by face-hh** [comment]
:smile:

**Pull request merged**
